### ISSUE TITLE
Two suggestions: rebase cef2go on atom/electron & renaming

### ISSUE THREAD

**Issue by h12w** [cztomczak/cef2go#26]
Two suggestions:

[atom/electron](https://github.com/atom/electron) seems to be a robust and well maintained project and could become a solid foundation for cef2go.

Also, Go lacks a standard GUI toolkit and cef2go could be a good choice, if that happens, then the name "cef2go" is not good enough.

**Comment by josephbudd** [comment]
Thanks for the reference to atom/electron.

**Comment by cztomczak** [comment]
CEF2go is described as a "GUI toolkit", but the main goal for this project as its name suggests, the "cef" part, is to provide Go bindings for the Chromium Embedded Framework.
